import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f2f2f7' },
    saveBtn: { fontWeight: '600' },
    content: { padding: 20, flex: 1 },
    contentContainer: { paddingBottom: 32, flexGrow: 1 },
    formGroup: { marginBottom: 20 },
    label: { fontSize: 14, color: '#666', marginBottom: 8, textTransform: 'uppercase' },
    input: {
        padding: 12,
        borderRadius: 10,
        fontSize: 16,
        borderWidth: 1,
        borderColor: 'transparent',
        backgroundColor: 'transparent',
    },
    textArea: { minHeight: 100, textAlignVertical: 'top' },
    row: { flexDirection: 'row', gap: 12 },
    flex1: { flex: 1 },
    dateRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    dateBtn: {
        backgroundColor: '#fff',
        padding: 12,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#e5e5e5',
    },
    clearDateBtn: {
        paddingHorizontal: 10,
        paddingVertical: 8,
        borderRadius: 8,
        backgroundColor: '#e5e5e5',
    },
    clearDateText: {
        fontSize: 12,
        color: '#333',
        fontWeight: '600',
    },
    statusContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    statusContainerCompact: {
        flexDirection: 'row',
        flexWrap: 'nowrap',
        justifyContent: 'space-between',
        gap: 6,
    },
    weekdayRow: { flexDirection: 'row', gap: 8 },
    weekdayButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    ordinalButton: {
        minWidth: 54,
        paddingHorizontal: 12,
        height: 44,
        borderRadius: 22,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    weekdayButtonText: {
        fontSize: 12,
        fontWeight: '600',
    },
    statusChip: {
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 16,
        borderWidth: 1,
        minHeight: 44,
        justifyContent: 'center',
    },
    statusChipCompact: {
        paddingHorizontal: 8,
        paddingVertical: 10,
        borderRadius: 14,
        borderWidth: 1,
        minWidth: 0,
        flex: 1,
        alignItems: 'center',
        minHeight: 44,
        justifyContent: 'center',
    },
    statusChipActive: { backgroundColor: '#007AFF' },
    statusText: { fontSize: 14, color: '#333' },
    statusTextActive: { color: '#fff' },
    startBtn: {
        backgroundColor: '#34C759',
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 16,
        minHeight: 44,
        justifyContent: 'center',
    },
    startBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
    doneBtn: {
        backgroundColor: '#007AFF',
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 16,
        minHeight: 44,
        justifyContent: 'center',
    },
    doneBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
    tokenSuggestionsMenu: {
        marginTop: 8,
        borderRadius: 10,
        borderWidth: 1,
        overflow: 'hidden',
    },
    tokenSuggestionItem: {
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(148, 163, 184, 0.2)',
    },
    tokenSuggestionItemLast: {
        borderBottomWidth: 0,
    },
    tokenSuggestionText: {
        fontSize: 14,
        fontWeight: '500',
    },
    quickTokensRow: {
        marginTop: 10,
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    quickTokenChip: {
        paddingHorizontal: 10,
        paddingVertical: 10,
        borderRadius: 14,
        borderWidth: 1,
        minHeight: 44,
        justifyContent: 'center',
    },
    quickTokenText: {
        fontSize: 13,
        fontWeight: '500',
    },
    checklistContainer: {
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 8,
        borderWidth: 1,
        borderColor: '#e5e5e5',
    },
    checklistItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    checkboxTouch: {
        padding: 4,
        minWidth: 44,
        minHeight: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },
    checkbox: {
        width: 28,
        height: 28,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: '#007AFF',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
        backgroundColor: 'transparent',
    },
    checkboxChecked: {
        backgroundColor: '#007AFF',
    },
    checkmark: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
    checklistInput: {
        flex: 1,
        fontSize: 16,
        padding: 0,
    },
    completedText: {
        textDecorationLine: 'line-through',
        color: '#999',
    },
    deleteBtn: {
        padding: 8,
        minWidth: 44,
        minHeight: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },
    deleteBtnText: {
        fontSize: 20,
        color: '#999',
        fontWeight: '300',
    },
    addChecklistBtn: {
        paddingVertical: 12,
        alignItems: 'center',
    },
    addChecklistText: {
        color: '#007AFF',
        fontSize: 15,
        fontWeight: '500',
    },
    aiRow: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 12,
    },
    aiButton: {
        borderWidth: 1,
        borderRadius: 16,
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    aiButtonText: {
        fontSize: 12,
        fontWeight: '600',
    },
    aiWorking: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingLeft: 4,
    },
    aiWorkingText: {
        fontSize: 12,
        fontWeight: '500',
    },
    emptySectionHint: {
        borderWidth: 1,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    emptySectionHintText: {
        fontSize: 12,
        fontWeight: '500',
    },
    copilotPill: {
        borderWidth: 1,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginBottom: 12,
    },
    copilotText: {
        fontSize: 12,
        fontWeight: '600',
    },
    copilotHint: {
        fontSize: 11,
        marginTop: 2,
    },
    pickerToolbar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        paddingVertical: 8,
    },
    pickerSpacer: {
        flex: 1,
    },
    pickerDone: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        backgroundColor: '#007AFF',
    },
    pickerDoneText: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '600',
    },
    checklistActions: {
        flexDirection: 'row',
        gap: 8,
        justifyContent: 'flex-start',
        paddingHorizontal: 4,
        paddingTop: 6,
    },
    checklistActionButton: {
        borderRadius: 12,
        borderWidth: 1,
        paddingHorizontal: 12,
        paddingVertical: 10,
        minHeight: 44,
        justifyContent: 'center',
    },
    checklistActionText: {
        fontSize: 12,
        fontWeight: '500',
    },
    inlineHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    inlineAction: {
        fontSize: 12,
        fontWeight: '700',
    },
    inlineActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    smallButton: {
        paddingHorizontal: 10,
        paddingVertical: 10,
        borderRadius: 8,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#e5e5e5',
        minHeight: 44,
        justifyContent: 'center',
    },
    smallButtonText: {
        fontSize: 12,
        fontWeight: '600',
    },
    markdownPreview: {
        marginTop: 8,
        padding: 12,
        borderRadius: 10,
        borderWidth: 1,
    },
    viewRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderWidth: 1,
        borderRadius: 10,
        marginBottom: 12,
    },
    viewLabel: {
        fontSize: 12,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.4,
        flex: 1,
    },
    viewValue: {
        fontSize: 14,
        fontWeight: '600',
        flex: 1,
        textAlign: 'right',
    },
    tabContent: {
        flex: 1,
    },
    tabPager: {
        flexDirection: 'row',
        flex: 1,
    },
    tabPage: {
        flex: 1,
    },
    viewSection: {
        marginBottom: 16,
    },
    viewPillRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 8,
    },
    viewPill: {
        borderWidth: 1,
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    viewPillText: {
        fontSize: 12,
        fontWeight: '600',
    },
    viewCard: {
        marginTop: 8,
        borderWidth: 1,
        borderRadius: 10,
        padding: 12,
    },
    viewChecklist: {
        marginTop: 8,
        gap: 6,
    },
    viewChecklistItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingVertical: 6,
    },
    viewChecklistMarker: {
        fontSize: 20,
        width: 26,
        height: 26,
        textAlign: 'center',
    },
    viewChecklistText: {
        fontSize: 14,
        flex: 1,
    },
    viewAttachmentGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginTop: 8,
    },
    viewAttachmentCard: {
        width: '48%',
        borderWidth: 1,
        borderRadius: 12,
        padding: 10,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 90,
    },
    viewAttachmentImage: {
        width: '100%',
        height: 90,
        borderRadius: 10,
        resizeMode: 'cover',
    },
    viewAttachmentText: {
        fontSize: 12,
        fontWeight: '600',
        textAlign: 'center',
    },
    viewAttachmentSubtext: {
        fontSize: 11,
        marginTop: 6,
        textAlign: 'center',
    },
    moreOptionsButton: {
        borderWidth: 1,
        borderRadius: 12,
        paddingVertical: 12,
        alignItems: 'center',
        marginTop: 4,
    },
    moreOptionsText: {
        fontSize: 14,
        fontWeight: '700',
    },
    helperText: {
        fontSize: 13,
        marginTop: 6,
    },
    attachmentsList: {
        marginTop: 8,
        borderWidth: 1,
        borderColor: '#e5e5e5',
        borderRadius: 10,
        overflow: 'hidden',
        backgroundColor: '#fff',
    },
    attachmentRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderBottomWidth: 1,
    },
    attachmentTitleWrap: {
        flex: 1,
        paddingRight: 10,
    },
    attachmentTitle: {
        fontSize: 13,
        fontWeight: '600',
    },
    attachmentDownload: {
        fontSize: 12,
        fontWeight: '600',
        marginRight: 10,
    },
    attachmentStatus: {
        fontSize: 12,
        fontWeight: '500',
        marginRight: 10,
    },
    attachmentRemove: {
        fontSize: 12,
        fontWeight: '600',
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.45)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalCard: {
        width: '100%',
        maxWidth: 420,
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
    },
    modalTitle: {
        fontSize: 16,
        fontWeight: '700',
        marginBottom: 12,
    },
    modalLabel: {
        fontSize: 13,
        fontWeight: '600',
    },
    modalInput: {
        borderWidth: 1,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 16,
    },
    customRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        flexWrap: 'wrap',
    },
    customInput: {
        borderWidth: 1,
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 6,
        fontSize: 14,
        minWidth: 64,
        textAlign: 'center',
    },
    modalButtons: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 12,
        marginTop: 14,
    },
    modalButton: {
        paddingHorizontal: 10,
        paddingVertical: 10,
        borderRadius: 10,
        minHeight: 44,
        justifyContent: 'center',
    },
    modalButtonText: {
        fontSize: 14,
        fontWeight: '700',
    },
    modalButtonDisabled: {
        opacity: 0.5,
    },
    pickerList: {
        marginTop: 12,
        borderRadius: 12,
        borderWidth: 1,
        maxHeight: 260,
    },
    pickerItem: {
        paddingVertical: 10,
        paddingHorizontal: 14,
    },
    pickerItemText: {
        fontSize: 16,
    },
});
