export const labelFallback = {
    en: {
        title: 'Settings',
        general: 'General',
        subtitle: 'Customize your Mindwtr experience',
        back: 'Back',
        features: 'Features',
        featuresDesc: 'Optional signals you can turn on when needed.',
        appearance: 'Appearance',
        gtd: 'GTD',
        gtdDesc: 'Tune the GTD workflow defaults.',
        captureDefault: 'Default capture method',
        captureDefaultDesc: 'Choose whether quick capture starts with text or audio.',
        captureDefaultText: 'Text',
        captureDefaultAudio: 'Audio',
        captureSaveAudio: 'Save audio attachments',
        captureSaveAudioDesc: 'Keep the audio file attached after transcription.',
        autoArchive: 'Auto-archive done tasks',
        autoArchiveDesc: 'Move completed tasks to Archived after a set number of days.',
        autoArchiveNever: 'Never (keep in Done)',
        language: 'Language',
        keybindings: 'Keyboard Shortcuts',
        keybindingsDesc: 'Choose your preferred desktop keybinding style.',
        keybindingVim: 'Vim',
        keybindingEmacs: 'Emacs',
        viewShortcuts: 'View shortcuts',
        taskEditorLayout: 'Task editor layout',
        taskEditorLayoutDesc: 'Choose which fields are shown by default in the task editor.',
        taskEditorLayoutHint: 'Hidden fields appear when they have content or after clicking “More options”.',
        taskEditorLayoutReset: 'Reset layout',
        taskEditorFieldStatus: 'Status',
        taskEditorFieldProject: 'Project',
        taskEditorFieldPriority: 'Priority',
        taskEditorFieldContexts: 'Contexts',
        taskEditorFieldDescription: 'Description',
        taskEditorFieldTags: 'Tags',
        taskEditorFieldTimeEstimate: 'Time estimate',
        taskEditorFieldRecurrence: 'Recurrence',
        taskEditorFieldStartTime: 'Start date',
        taskEditorFieldDueDate: 'Due date',
        taskEditorFieldReviewAt: 'Review date',
        taskEditorFieldAttachments: 'Attachments',
        taskEditorFieldChecklist: 'Checklist',
        taskEditorFieldTextDirection: 'Text direction',
        featurePriorities: 'Priorities',
        featurePrioritiesDesc: 'Show a priority flag on tasks.',
        featureTimeEstimates: 'Time estimates',
        featureTimeEstimatesDesc: 'Add quick duration estimates for time blocking.',
        notifications: 'Notifications',
        notificationsDesc: 'Enable task reminders and daily digest notifications.',
        notificationsEnable: 'Enable notifications',
        ai: 'AI Assistant',
        aiDesc: 'Optional help to clarify and break down tasks.',
        aiEnable: 'Enable AI assistant',
        aiProvider: 'Provider',
        aiProviderOpenAI: 'OpenAI',
        aiProviderGemini: 'Gemini',
        aiProviderAnthropic: 'Anthropic (Claude)',
        aiModel: 'Model',
        aiApiKey: 'API key',
        aiApiKeyHint: 'Stored locally on this device. Never synced.',
        aiReasoning: 'Reasoning effort',
        aiReasoningHint: 'Used by GPT-5 models.',
        aiEffortLow: 'Low',
        aiEffortMedium: 'Medium',
        aiEffortHigh: 'High',
        aiCopilotModel: 'Copilot model',
        aiCopilotHint: 'Used for fast autocomplete suggestions.',
        aiThinkingBudget: 'Thinking budget',
        aiThinkingHint: 'Claude/Gemini only. 0 disables extended thinking.',
        aiThinkingEnable: 'Enable thinking',
        aiThinkingEnableDesc: 'Use extended reasoning for complex tasks.',
        aiThinkingOff: 'Off',
        aiThinkingLow: 'Low',
        aiThinkingMedium: 'Medium',
        aiThinkingHigh: 'High',
        speechTitle: 'Speech to text',
        speechDesc: 'Transcribe voice captures and map them into task fields.',
        speechEnable: 'Enable speech to text',
        speechProvider: 'Speech provider',
        speechProviderOffline: 'On-device (Whisper)',
        speechModel: 'Speech model',
        speechOfflineModel: 'Offline model',
        speechOfflineModelDesc: 'Download once to transcribe fully offline.',
        speechOfflineReady: 'Model downloaded',
        speechOfflineNotDownloaded: 'Model not downloaded',
        speechOfflineDownload: 'Download',
        speechOfflineDownloadSuccess: 'Download complete',
        speechOfflineDelete: 'Delete',
        speechOfflineDownloadError: 'Offline model download failed',
        speechLanguage: 'Audio language',
        speechLanguageHint: 'Use a language name or code, or leave blank to auto-detect.',
        speechLanguageAuto: 'Auto (detect language)',
        speechMode: 'Processing mode',
        speechModeHint: 'Smart parse extracts dates and fields; transcript-only just transcribes.',
        speechModeSmart: 'Smart parse',
        speechModeTranscript: 'Transcript only',
        speechFieldStrategy: 'Field mapping',
        speechFieldStrategyHint: 'Choose where the transcript should land by default.',
        speechFieldSmart: 'Smart',
        speechFieldTitle: 'Title',
        speechFieldDescription: 'Description',
        dailyDigest: 'Daily Digest',
        dailyDigestDesc: 'Morning briefing and evening review prompts.',
        dailyDigestMorning: 'Morning briefing',
        dailyDigestEvening: 'Evening review',
        weeklyReview: 'Weekly review',
        weeklyReviewDesc: 'Get a weekly review reminder at your chosen time.',
        weeklyReviewDay: 'Review day',
        weeklyReviewTime: 'Review time',
        on: 'On',
        off: 'Off',
        visible: 'Shown',
        hidden: 'Hidden',
        manage: 'Manage',
        localData: 'Local Data',
        localDataDesc: 'Config is stored in your system config folder; data is stored in your system data folder.',
        webDataDesc: 'The web app stores data in browser storage.',
        diagnostics: 'Diagnostics',
        diagnosticsDesc: 'Help troubleshoot issues.',
        debugLogging: 'Debug logging',
        debugLoggingDesc: 'Record errors locally to share with support.',
        logFile: 'Log file',
        clearLog: 'Clear log',
        sync: 'Sync',
        syncDescription:
            'Configure a secondary folder to sync your data with (e.g., Dropbox, Syncthing). This merges your local data with the sync folder to prevent data loss.',
        syncBackend: 'Sync backend',
        syncBackendFile: 'File',
        syncBackendWebdav: 'WebDAV',
        syncBackendCloud: 'Self-Hosted',
        attachmentsCleanup: 'Attachment cleanup',
        attachmentsCleanupDesc: 'Remove deleted or orphaned attachment files from your device and sync storage.',
        attachmentsCleanupLastRun: 'Last cleanup',
        attachmentsCleanupNever: 'Never',
        attachmentsCleanupRun: 'Run cleanup',
        attachmentsCleanupRunning: 'Cleaning...',
        calendar: 'Calendar',
        calendarDesc: 'View external calendars via ICS subscription URLs.',
        externalCalendars: 'External calendars',
        calendarName: 'Name',
        calendarUrl: 'ICS URL',
        calendarAdd: 'Add calendar',
        calendarRemove: 'Remove',
        syncFolderLocation: 'Sync folder',
        savePath: 'Save',
        browse: 'Browse…',
        syncNow: 'Sync now',
        syncing: 'Syncing…',
        pathHint: 'Type a path directly (e.g., ~/Sync/mindwtr) or use Browse if available',
        webdavUrl: 'WebDAV URL',
        webdavUsername: 'Username',
        webdavPassword: 'Password',
        webdavSave: 'Save WebDAV',
        webdavHint: 'Point to a folder — Mindwtr will store data.json inside (e.g., https://example.com/remote.php/dav/files/user/mindwtr).',
        cloudUrl: 'Self-hosted URL',
        cloudToken: 'Access token',
        cloudSave: 'Save Self-Hosted',
        cloudHint: 'Use the base endpoint URL (e.g., https://example.com/v1). Mindwtr will append /data.',
        lastSync: 'Last sync',
        lastSyncNever: 'Never',
        lastSyncSuccess: 'Sync completed',
        lastSyncError: 'Sync failed',
        lastSyncConflict: 'Conflicts resolved',
        lastSyncConflicts: 'Conflicts',
        about: 'About',
        version: 'Version',
        developer: 'Developer',
        website: 'Website',
        github: 'GitHub',
        license: 'License',
        checkForUpdates: 'Check for Updates',
        checking: 'Checking…',
        upToDate: 'You are using the latest version!',
        updateAvailable: 'Update Available',
        checkFailed: 'Failed to check for updates',
        download: 'Download',
        downloadStarting: 'Opening download…',
        downloadStarted: 'Download started in your browser.',
        downloadFailed: 'Failed to open download link.',
        downloadRecommended: 'Recommended package',
        downloadAURHint: 'Arch detected: update via AUR',
        changelog: 'Changelog',
        noChangelog: 'No changelog available',
        later: 'Later',
        linuxUpdateHint: 'On Linux, Mindwtr cannot auto-install updates. After downloading, install via your package manager (e.g., yay -S mindwtr or paru -S mindwtr) or the downloaded package.',
        saved: 'Settings saved',
        selectSyncFolderTitle: 'Select sync folder',
        system: 'System',
        light: 'Light',
        dark: 'Dark',
        eink: 'E-Ink',
        nord: 'Nord',
        sepia: 'Sepia',
    },
    zh: {
        title: '设置',
        general: '通用',
        subtitle: '自定义您的 Mindwtr 体验',
        back: '返回',
        features: '功能',
        featuresDesc: '按需开启可选信号。',
        appearance: '外观',
        gtd: 'GTD',
        gtdDesc: '调整 GTD 工作流默认设置。',
        captureDefault: '默认捕获方式',
        captureDefaultDesc: '选择快速捕获默认使用文本或语音。',
        captureDefaultText: '文本',
        captureDefaultAudio: '语音',
        captureSaveAudio: '保留语音附件',
        captureSaveAudioDesc: '转录后仍保留音频文件。',
        autoArchive: '自动归档完成任务',
        autoArchiveDesc: '在设定天数后将已完成任务移入归档。',
        autoArchiveNever: '从不（保留在已完成）',
        language: '语言',
        keybindings: '快捷键',
        keybindingsDesc: '选择桌面端偏好的快捷键风格。',
        keybindingVim: 'Vim',
        keybindingEmacs: 'Emacs',
        viewShortcuts: '查看快捷键',
        taskEditorLayout: '任务编辑布局',
        taskEditorLayoutDesc: '选择默认显示的任务编辑字段。',
        taskEditorLayoutHint: '隐藏字段仅在有内容或点击“更多选项”后显示。',
        taskEditorLayoutReset: '重置布局',
        taskEditorFieldStatus: '状态',
        taskEditorFieldProject: '项目',
        taskEditorFieldPriority: '优先级',
        taskEditorFieldContexts: '情境',
        taskEditorFieldDescription: '描述',
        taskEditorFieldTags: '标签',
        taskEditorFieldTimeEstimate: '时间预估',
        taskEditorFieldRecurrence: '重复',
        taskEditorFieldStartTime: '开始日期',
        taskEditorFieldDueDate: '截止日期',
        taskEditorFieldReviewAt: '回顾日期',
        taskEditorFieldAttachments: '附件',
        taskEditorFieldChecklist: '清单',
        taskEditorFieldTextDirection: '文本方向',
        featurePriorities: '优先级',
        featurePrioritiesDesc: '为任务显示优先级标记。',
        featureTimeEstimates: '时间估算',
        featureTimeEstimatesDesc: '为时间管理添加时长估计。',
        notifications: '通知',
        notificationsDesc: '启用任务提醒与每日简报通知。',
        notificationsEnable: '启用通知',
        ai: 'AI 助手',
        aiDesc: '帮助澄清与拆解任务（可选）。',
        aiEnable: '启用 AI 助手',
        aiProvider: '服务商',
        aiProviderOpenAI: 'OpenAI',
        aiProviderGemini: 'Gemini',
        aiProviderAnthropic: 'Anthropic（Claude）',
        aiModel: '模型',
        aiApiKey: 'API 密钥',
        aiApiKeyHint: '仅保存在本机，不会同步。',
        aiReasoning: '推理强度',
        aiReasoningHint: '仅用于 GPT-5 模型。',
        aiEffortLow: '低',
        aiEffortMedium: '中',
        aiEffortHigh: '高',
        aiCopilotModel: '助手模型',
        aiCopilotHint: '用于快速补全建议。',
        aiThinkingBudget: '思考预算',
        aiThinkingHint: '仅用于 Claude/Gemini。0 代表关闭深度思考。',
        aiThinkingEnable: '启用思考',
        aiThinkingEnableDesc: '为复杂任务启用扩展推理。',
        aiThinkingOff: '关闭',
        aiThinkingLow: '低',
        aiThinkingMedium: '中',
        aiThinkingHigh: '高',
        speechTitle: '语音转文字',
        speechDesc: '转录语音并映射到任务字段。',
        speechEnable: '启用语音转文字',
        speechProvider: '语音服务商',
        speechProviderOffline: '本地（Whisper）',
        speechModel: '语音模型',
        speechOfflineModel: '离线模型',
        speechOfflineModelDesc: '下载一次即可离线转录。',
        speechOfflineReady: '模型已下载',
        speechOfflineNotDownloaded: '尚未下载模型',
        speechOfflineDownload: '下载',
        speechOfflineDownloadSuccess: '下载完成',
        speechOfflineDelete: '删除',
        speechOfflineDownloadError: '离线模型下载失败',
        speechLanguage: '语音语言',
        speechLanguageHint: '可填写语言名称或代码，留空则自动检测。',
        speechLanguageAuto: '自动检测语言',
        speechMode: '处理模式',
        speechModeHint: '智能解析可提取日期与字段，纯转录仅输出文本。',
        speechModeSmart: '智能解析',
        speechModeTranscript: '仅转录',
        speechFieldStrategy: '字段映射',
        speechFieldStrategyHint: '选择默认写入标题或描述的位置。',
        speechFieldSmart: '智能',
        speechFieldTitle: '标题',
        speechFieldDescription: '描述',
        dailyDigest: '每日简报',
        dailyDigestDesc: '早间简报与晚间回顾提醒。',
        dailyDigestMorning: '早间简报',
        dailyDigestEvening: '晚间回顾',
        weeklyReview: '每周回顾',
        weeklyReviewDesc: '在你设定的时间提醒进行每周回顾。',
        weeklyReviewDay: '回顾日期',
        weeklyReviewTime: '回顾时间',
        on: '开启',
        off: '关闭',
        visible: '显示',
        hidden: '隐藏',
        manage: '管理',
        localData: '本地数据',
        localDataDesc: '配置保存在系统配置目录；数据保存在系统数据目录。',
        webDataDesc: 'Web 版本使用浏览器存储。',
        diagnostics: '诊断',
        diagnosticsDesc: '帮助排查问题。',
        debugLogging: '调试日志',
        debugLoggingDesc: '将错误记录到本地以便提交反馈。',
        logFile: '日志文件',
        clearLog: '清除日志',
        sync: '同步',
        syncDescription:
            '配置一个辅助文件夹来同步您的数据（如 Dropbox、Syncthing）。这会将本地数据与同步文件夹合并，以防止数据丢失。',
        syncBackend: '同步后端',
        syncBackendFile: '文件',
        syncBackendWebdav: 'WebDAV',
        syncBackendCloud: '自托管',
        attachmentsCleanup: '附件清理',
        attachmentsCleanupDesc: '从设备和同步存储中删除已删除或孤立的附件文件。',
        attachmentsCleanupLastRun: '上次清理',
        attachmentsCleanupNever: '从未',
        attachmentsCleanupRun: '立即清理',
        attachmentsCleanupRunning: '清理中...',
        calendar: '日历',
        calendarDesc: '通过 ICS 订阅地址查看外部日历（只读）。',
        externalCalendars: '外部日历',
        calendarName: '名称',
        calendarUrl: 'ICS 地址',
        calendarAdd: '添加日历',
        calendarRemove: '移除',
        syncFolderLocation: '同步文件夹',
        savePath: '保存',
        browse: '浏览…',
        syncNow: '立即同步',
        syncing: '同步中…',
        pathHint: '直接输入路径（如 ~/Sync/mindwtr）或点击浏览选择',
        webdavUrl: 'WebDAV 地址',
        webdavUsername: '用户名',
        webdavPassword: '密码',
        webdavSave: '保存 WebDAV',
        webdavHint: '请输入同步文件夹地址，Mindwtr 会在其中存放 data.json（例如 https://example.com/remote.php/dav/files/user/mindwtr）。',
        cloudUrl: '自托管地址',
        cloudToken: '访问令牌',
        cloudSave: '保存自托管配置',
        cloudHint: '请输入自托管基础地址（例如 https://example.com/v1），Mindwtr 会自动追加 /data。',
        lastSync: '上次同步',
        lastSyncNever: '从未同步',
        lastSyncSuccess: '同步完成',
        lastSyncError: '同步失败',
        lastSyncConflict: '已解决冲突',
        lastSyncConflicts: '冲突',
        about: '关于',
        version: '版本',
        developer: '开发者',
        website: '网站',
        github: 'GitHub',
        license: '许可证',
        checkForUpdates: '检查更新',
        checking: '检查中…',
        upToDate: '您正在使用最新版本！',
        updateAvailable: '有可用更新',
        checkFailed: '检查更新失败',
        download: '下载',
        downloadStarting: '正在打开下载…',
        downloadStarted: '已在浏览器开始下载。',
        downloadFailed: '打开下载链接失败。',
        downloadRecommended: '推荐下载包',
        downloadAURHint: '检测到 Arch：建议使用 AUR 更新',
        changelog: '更新日志',
        noChangelog: '暂无更新日志',
        later: '稍后',
        linuxUpdateHint: 'Linux 上无法自动安装更新。下载后请使用包管理器更新（如 yay -S mindwtr 或 paru -S mindwtr），或安装下载的包。',
        saved: '设置已保存',
        selectSyncFolderTitle: '选择同步文件夹',
        system: '系统',
        light: '浅色',
        dark: '深色',
        eink: '电子墨水',
        nord: 'Nord',
        sepia: '复古米黄',
    },
} as const;

export type SettingsLabels = Record<keyof typeof labelFallback.en, string>;

export const labelKeyOverrides: Partial<Record<keyof SettingsLabels, string>> = {
    back: 'common.back',
    keybindings: 'keybindings.helpTitle',
    keybindingsDesc: 'settings.keybindingsDesc',
    keybindingVim: 'keybindings.style.vim',
    keybindingEmacs: 'keybindings.style.emacs',
    viewShortcuts: 'keybindings.openHelp',
    taskEditorLayoutReset: 'settings.resetToDefault',
    taskEditorFieldStatus: 'taskEdit.statusLabel',
    taskEditorFieldProject: 'taskEdit.projectLabel',
    taskEditorFieldPriority: 'taskEdit.priorityLabel',
    taskEditorFieldContexts: 'taskEdit.contextsLabel',
    taskEditorFieldDescription: 'taskEdit.descriptionLabel',
    taskEditorFieldTags: 'taskEdit.tagsLabel',
    taskEditorFieldTimeEstimate: 'taskEdit.timeEstimateLabel',
    taskEditorFieldRecurrence: 'taskEdit.recurrenceLabel',
    taskEditorFieldStartTime: 'taskEdit.startDateLabel',
    taskEditorFieldDueDate: 'taskEdit.dueDateLabel',
    taskEditorFieldReviewAt: 'taskEdit.reviewDateLabel',
    taskEditorFieldAttachments: 'attachments.title',
    taskEditorFieldChecklist: 'taskEdit.checklist',
    taskEditorFieldTextDirection: 'taskEdit.textDirectionLabel',
} as const;
