export const labelFallback = {
    en: {
        title: 'Settings',
        general: 'General',
        subtitle: 'Customize your Mindwtr experience',
        searchPlaceholder: 'Search settings…',
        back: 'Back',
        features: 'Features',
        featuresDesc: 'Optional signals you can turn on when needed.',
        lookAndFeel: 'Look & Feel',
        localization: 'Localization',
        input: 'Input',
        windowBehavior: 'Window Behavior',
        appearance: 'Appearance',
        density: 'Density',
        densityDesc: 'Adjust list spacing to show more items on screen.',
        densityComfortable: 'Comfortable',
        densityCompact: 'Compact',
        gtd: 'GTD',
        gtdDesc: 'Tune the GTD workflow defaults.',
        inboxProcessing: 'Inbox processing',
        inboxProcessingDesc: 'Customize the inbox workflow to match your style.',
        inboxTwoMinuteFirst: 'Ask the 2-minute rule first',
        inboxProjectFirst: 'Ask for project early',
        inboxScheduleEnabled: 'Allow scheduling during processing',
        captureDefault: 'Default capture method',
        captureDefaultDesc: 'Choose whether quick capture starts with text or audio.',
        captureDefaultText: 'Text',
        captureDefaultAudio: 'Audio',
        captureSaveAudio: 'Save audio attachments',
        captureSaveAudioDesc: 'Keep the audio file attached after transcription.',
        autoArchive: 'Auto-archive done tasks',
        autoArchiveDesc: 'Move completed tasks to Archived after a set number of days.',
        autoArchiveNever: 'Never (keep in Done)',
        language: 'Language',
        weekStart: 'Week starts on',
        weekStartSunday: 'Sunday',
        weekStartMonday: 'Monday',
        dateFormat: 'Date format',
        dateFormatSystem: 'System default',
        dateFormatDmy: 'Day / Month / Year',
        dateFormatMdy: 'Month / Day / Year',
        keybindings: 'Keyboard Shortcuts',
        keybindingsDesc: 'Choose your preferred desktop keybinding style.',
        undoNotifications: 'Undo notifications',
        undoNotificationsDesc: 'Show an Undo toast after marking tasks Done or deleting tasks.',
        globalQuickAddShortcut: 'Global quick add shortcut',
        globalQuickAddShortcutDesc: 'Used system-wide for quick capture, even when Mindwtr is not focused.',
        keybindingVim: 'Vim',
        keybindingEmacs: 'Emacs',
        viewShortcuts: 'View shortcuts',
        windowDecorations: 'Window decorations',
        windowDecorationsDesc: 'Show system title bar and window borders.',
        closeBehavior: 'Close window behavior',
        closeBehaviorDesc: 'Choose what happens when you close the window.',
        closeBehaviorAsk: 'Ask every time',
        closeBehaviorTray: 'Keep running in tray',
        closeBehaviorQuit: 'Quit the app',
        showTray: 'Show system tray icon',
        showTrayDesc: 'Display the app icon in your system tray for quick access.',
        taskEditorLayout: 'Task editor layout',
        taskEditorLayoutDesc: 'Choose which fields are shown by default in the task editor.',
        taskEditorLayoutHint: 'Hidden fields appear when they have content or after clicking “More options”.',
        taskEditorLayoutReset: 'Reset layout',
        taskEditorFieldStatus: 'Status',
        taskEditorFieldProject: 'Project',
        taskEditorFieldSection: 'Section',
        taskEditorFieldArea: 'Area',
        taskEditorFieldPriority: 'Priority',
        taskEditorFieldContexts: 'Contexts',
        taskEditorFieldDescription: 'Description',
        taskEditorFieldTags: 'Tags',
        taskEditorFieldTimeEstimate: 'Time estimate',
        taskEditorFieldRecurrence: 'Recurrence',
        taskEditorFieldStartTime: 'Start date',
        taskEditorFieldDueDate: 'Due date',
        taskEditorFieldReviewAt: 'Review date',
        taskEditorFieldAttachments: 'Attachments',
        taskEditorFieldChecklist: 'Checklist',
        taskEditorFieldTextDirection: 'Text direction',
        featurePriorities: 'Priorities',
        featurePrioritiesDesc: 'Show a priority flag on tasks.',
        featureTimeEstimates: 'Time estimates',
        featureTimeEstimatesDesc: 'Add quick duration estimates for time blocking.',
        featurePomodoro: 'Pomodoro timer',
        featurePomodoroDesc: 'Enable the optional Pomodoro panel in Focus view.',
        notifications: 'Notifications',
        notificationsDesc: 'Enable task reminders and daily digest notifications.',
        notificationsEnable: 'Enable notifications',
        reviewAtNotifications: 'Review date reminders',
        reviewAtNotificationsDesc: 'Notify me when a review (tickler) date is due.',
        ai: 'AI Assistant',
        aiDesc: 'Optional help to clarify and break down tasks.',
        aiEnable: 'Enable AI assistant',
        aiProvider: 'Provider',
        aiProviderOpenAI: 'OpenAI',
        aiProviderGemini: 'Gemini',
        aiProviderAnthropic: 'Anthropic (Claude)',
        aiModel: 'Model',
        aiBaseUrl: 'Custom base URL',
        aiBaseUrlHint: 'Optional. For local OpenAI-compatible servers (e.g., http://localhost:11434/v1).',
        aiApiKey: 'API key',
        aiApiKeyHint: 'Stored locally on this device. Never synced. For local endpoints, leave blank if auth is not required.',
        aiReasoning: 'Reasoning effort',
        aiReasoningHint: 'Used by GPT-5 models.',
        aiEffortLow: 'Low',
        aiEffortMedium: 'Medium',
        aiEffortHigh: 'High',
        aiCopilotModel: 'Copilot model',
        aiCopilotHint: 'Used for fast autocomplete suggestions.',
        aiConsentTitle: 'Enable AI Features?',
        aiConsentDescription: 'To use this feature, your task data will be sent to {provider} for processing. This data is subject to their privacy policy. Mindwtr does not collect this data. Do you wish to proceed?',
        aiConsentCancel: 'Cancel',
        aiConsentAgree: 'Agree',
        aiThinkingBudget: 'Thinking budget',
        aiThinkingHint: 'Claude/Gemini only. 0 disables extended thinking.',
        aiThinkingEnable: 'Enable thinking',
        aiThinkingEnableDesc: 'Use extended reasoning for complex tasks.',
        aiThinkingOff: 'Off',
        aiThinkingLow: 'Low',
        aiThinkingMedium: 'Medium',
        aiThinkingHigh: 'High',
        speechTitle: 'Speech to text',
        speechDesc: 'Transcribe voice captures and map them into task fields.',
        speechEnable: 'Enable speech to text',
        speechProvider: 'Speech provider',
        speechProviderOffline: 'On-device (Whisper)',
        speechModel: 'Speech model',
        speechOfflineModel: 'Offline model',
        speechOfflineModelDesc: 'Download once to transcribe fully offline.',
        speechOfflineReady: 'Model downloaded',
        speechOfflineNotDownloaded: 'Model not downloaded',
        speechOfflineDownload: 'Download',
        speechOfflineDownloadSuccess: 'Download complete',
        speechOfflineDelete: 'Delete',
        speechOfflineDownloadError: 'Offline model download failed',
        speechLanguage: 'Audio language',
        speechLanguageHint: 'Use a language name or code, or leave blank to auto-detect.',
        speechLanguageAuto: 'Auto (detect language)',
        speechMode: 'Processing mode',
        speechModeHint: 'Smart parse extracts dates and fields; transcript-only just transcribes.',
        speechModeSmart: 'Smart parse',
        speechModeTranscript: 'Transcript only',
        speechFieldStrategy: 'Field mapping',
        speechFieldStrategyHint: 'Choose where the transcript should land by default.',
        speechFieldSmart: 'Smart',
        speechFieldTitle: 'Title',
        speechFieldDescription: 'Description',
        dailyDigest: 'Daily Digest',
        dailyDigestDesc: 'Morning briefing and evening review prompts.',
        dailyDigestMorning: 'Morning briefing',
        dailyDigestEvening: 'Evening review',
        weeklyReview: 'Weekly review',
        weeklyReviewDesc: 'Get a weekly review reminder at your chosen time.',
        weeklyReviewDay: 'Review day',
        weeklyReviewTime: 'Review time',
        weeklyReviewConfig: 'Weekly review flow',
        weeklyReviewConfigDesc: 'Configure which steps appear in weekly review.',
        weeklyReviewIncludeContextsStep: 'Include Contexts step',
        weeklyReviewIncludeContextsStepDesc: 'Show a dedicated contexts review step between Waiting For and Projects.',
        on: 'On',
        off: 'Off',
        visible: 'Shown',
        hidden: 'Hidden',
        manage: 'Manage',
        diagnostics: 'Diagnostics',
        diagnosticsDesc: 'Help troubleshoot issues.',
        debugLogging: 'Debug logging',
        debugLoggingDesc: 'Record errors locally to share with support.',
        logFile: 'Log file',
        clearLog: 'Clear log',
        sync: 'Sync',
        syncDescription:
            'Configure a secondary folder to sync your data with (e.g., Dropbox, Syncthing). For near real-time multi-device sync, WebDAV is recommended over folder sync tools.',
        syncBackend: 'Sync backend',
        syncBackendOff: 'Off',
        syncBackendFile: 'File',
        syncBackendWebdav: 'WebDAV',
        syncBackendCloud: 'Self-Hosted',
        syncPreferences: 'Settings sync options',
        syncPreferencesDesc: 'Choose which preferences stay in sync across devices.',
        syncPreferenceAppearance: 'Appearance (theme, density)',
        syncPreferenceLanguage: 'Language & date format',
        syncPreferenceExternalCalendars: 'External calendar URLs',
        syncPreferenceAi: 'AI settings (models, providers)',
        syncPreferenceAiHint: 'API keys and local model paths are never synced.',
        attachmentsCleanup: 'Attachment cleanup',
        attachmentsCleanupDesc: 'Remove deleted or orphaned attachment files from your device and sync storage.',
        attachmentsCleanupLastRun: 'Last cleanup',
        attachmentsCleanupNever: 'Never',
        attachmentsCleanupRun: 'Run cleanup',
        attachmentsCleanupRunning: 'Cleaning...',
        calendar: 'Calendar',
        calendarDesc: 'View external calendars via ICS subscription URLs.',
        externalCalendars: 'External calendars',
        calendarName: 'Name',
        calendarUrl: 'ICS URL',
        calendarAdd: 'Add calendar',
        calendarRemove: 'Remove',
        calendarSystemTitle: 'Apple Calendar (macOS)',
        calendarSystemDesc: 'Read events from Apple Calendar accounts synced by macOS (iCloud, Google, Exchange) via EventKit.',
        calendarSystemStatus: 'Apple Calendar access',
        calendarSystemPermissionGranted: 'Granted',
        calendarSystemPermissionUndetermined: 'Not requested',
        calendarSystemPermissionDenied: 'Denied',
        calendarSystemPermissionUnsupported: 'Unsupported',
        calendarSystemRequestAccess: 'Request access',
        calendarSystemDeniedHint: 'Calendar access is denied. Enable Mindwtr in macOS System Settings > Privacy & Security > Calendars.',
        syncFolderLocation: 'Sync folder',
        savePath: 'Save',
        browse: 'Browse…',
        syncNow: 'Sync now',
        syncing: 'Syncing…',
        syncQueued: 'Sync queued',
        pathHint: 'Choose a folder (e.g., ~/Sync/mindwtr). With Syncthing: use Send & Receive + Watch for Changes, then press Sync now before switching devices.',
        webdavUrl: 'WebDAV URL',
        webdavUsername: 'Username',
        webdavPassword: 'Password',
        webdavSave: 'Save WebDAV',
        webdavHint: 'Point to a folder — Mindwtr will store data.json inside (e.g., https://example.com/remote.php/dav/files/user/mindwtr).',
        cloudUrl: 'Self-hosted URL',
        cloudToken: 'Access token',
        cloudSave: 'Save Self-Hosted',
        cloudHint: 'Use the base endpoint URL (e.g., https://example.com/v1). Mindwtr will append /data.',
        cloudProvider: 'Cloud provider',
        cloudProviderSelfHosted: 'Self-hosted',
        cloudProviderDropbox: 'Dropbox',
        dropboxAppKey: 'Dropbox account',
        dropboxAppKeyHint: 'Dropbox app key is injected at build/release time.',
        dropboxRedirectUri: 'Redirect URI',
        dropboxStatus: 'Status',
        dropboxConnected: 'Connected',
        dropboxNotConnected: 'Not connected',
        dropboxConnect: 'Connect Dropbox',
        dropboxDisconnect: 'Disconnect Dropbox',
        dropboxTest: 'Test connection',
        dropboxTestReachable: 'Reachable',
        dropboxTestFailed: 'Failed',
        lastSync: 'Last sync',
        lastSyncNever: 'Never',
        lastSyncSuccess: 'Sync completed',
        lastSyncError: 'Sync failed',
        lastSyncConflict: 'Conflicts resolved',
        lastSyncConflicts: 'Conflicts',
        lastSyncSkew: 'Clock skew',
        lastSyncAdjusted: 'Timestamp fixes',
        lastSyncConflictIds: 'Conflict IDs',
        syncHistory: 'Sync history',
        recoverySnapshots: 'Recovery snapshots',
        recoverySnapshotsDesc: 'Created before sync. Kept for up to 7 days (max 5 files).',
        recoverySnapshotsLoading: 'Loading snapshots…',
        recoverySnapshotsEmpty: 'No snapshots yet.',
        recoverySnapshotsRestore: 'Restore',
        recoverySnapshotsConfirm: 'Restore snapshot {snapshot}? This will replace current local data.',
        recoverySnapshotsConfirmTitle: 'Restore snapshot?',
        recoverySnapshotsConfirmCancel: 'Cancel',
        about: 'About',
        version: 'Version',
        developer: 'Developer',
        website: 'Developer Website',
        github: 'GitHub',
        documentation: 'Documentation',
        sponsorProject: 'Sponsor Project',
        license: 'License',
        checkForUpdates: 'Check for Updates',
        checkStoreUpdates: 'Check Microsoft Store',
        checking: 'Checking…',
        upToDate: 'You are using the latest version!',
        updateAvailable: 'Update Available',
        checkFailed: 'Failed to check for updates',
        storeUpdateHint: 'Updates are managed by Microsoft Store.',
        download: 'Download',
        downloadStarting: 'Opening download…',
        downloadStarted: 'Download started in your browser.',
        downloadFailed: 'Failed to open download link.',
        downloadChecksumMismatch: 'Checksum verification failed. Please download again from the release page.',
        downloadRecommended: 'Recommended package',
        downloadAURHint: 'Arch detected: update via AUR',
        changelog: 'Changelog',
        noChangelog: 'No changelog available',
        later: 'Later',
        linuxUpdateHint: 'On Linux, Mindwtr cannot auto-install updates. After downloading, install via your package manager (e.g., yay -S mindwtr or paru -S mindwtr) or the downloaded package.',
        saved: 'Settings saved',
        selectSyncFolderTitle: 'Select sync folder',
        system: 'System',
        light: 'Light',
        dark: 'Dark',
        eink: 'E-Ink',
        nord: 'Nord',
        sepia: 'Sepia',
    },
    zh: {
        title: '设置',
        general: '通用',
        subtitle: '自定义您的 Mindwtr 体验',
        searchPlaceholder: '搜索设置…',
        back: '返回',
        features: '功能',
        featuresDesc: '按需开启可选信号。',
        lookAndFeel: '外观与风格',
        localization: '本地化',
        input: '输入',
        windowBehavior: '窗口行为',
        appearance: '外观',
        density: '密度',
        densityDesc: '调整列表间距以显示更多内容。',
        densityComfortable: '舒适',
        densityCompact: '紧凑',
        gtd: 'GTD',
        gtdDesc: '调整 GTD 工作流默认设置。',
        inboxProcessing: '收集箱处理',
        inboxProcessingDesc: '按你的习惯调整收集箱处理流程。',
        inboxTwoMinuteFirst: '先询问两分钟规则',
        inboxProjectFirst: '提前询问项目归属',
        inboxScheduleEnabled: '处理中允许安排日期',
        captureDefault: '默认捕获方式',
        captureDefaultDesc: '选择快速捕获默认使用文本或语音。',
        captureDefaultText: '文本',
        captureDefaultAudio: '语音',
        captureSaveAudio: '保留语音附件',
        captureSaveAudioDesc: '转录后仍保留音频文件。',
        autoArchive: '自动归档完成任务',
        autoArchiveDesc: '在设定天数后将已完成任务移入归档。',
        autoArchiveNever: '从不（保留在已完成）',
        language: '语言',
        weekStart: '每周开始于',
        weekStartSunday: '周日',
        weekStartMonday: '周一',
        dateFormat: '日期格式',
        dateFormatSystem: '系统默认',
        dateFormatDmy: '日 / 月 / 年',
        dateFormatMdy: '月 / 日 / 年',
        keybindings: '快捷键',
        keybindingsDesc: '选择桌面端偏好的快捷键风格。',
        undoNotifications: '撤销通知',
        undoNotificationsDesc: '在将任务标记为已完成或删除后显示可撤销提示。',
        globalQuickAddShortcut: '全局快速添加快捷键',
        globalQuickAddShortcutDesc: '用于系统级快速收集，即使 Mindwtr 未聚焦也可触发。',
        keybindingVim: 'Vim',
        keybindingEmacs: 'Emacs',
        viewShortcuts: '查看快捷键',
        windowDecorations: '窗口装饰',
        windowDecorationsDesc: '显示系统标题栏和窗口边框。',
        closeBehavior: '关闭窗口行为',
        closeBehaviorDesc: '选择关闭窗口时的操作。',
        closeBehaviorAsk: '每次询问',
        closeBehaviorTray: '保留在托盘',
        closeBehaviorQuit: '退出应用',
        showTray: '显示系统托盘图标',
        showTrayDesc: '在系统托盘中显示应用图标以便快速访问。',
        taskEditorLayout: '任务编辑布局',
        taskEditorLayoutDesc: '选择默认显示的任务编辑字段。',
        taskEditorLayoutHint: '隐藏字段仅在有内容或点击“更多选项”后显示。',
        taskEditorLayoutReset: '重置布局',
        taskEditorFieldStatus: '状态',
        taskEditorFieldProject: '项目',
        taskEditorFieldSection: '分组',
        taskEditorFieldArea: '领域',
        taskEditorFieldPriority: '优先级',
        taskEditorFieldContexts: '情境',
        taskEditorFieldDescription: '描述',
        taskEditorFieldTags: '标签',
        taskEditorFieldTimeEstimate: '时间预估',
        taskEditorFieldRecurrence: '重复',
        taskEditorFieldStartTime: '开始日期',
        taskEditorFieldDueDate: '截止日期',
        taskEditorFieldReviewAt: '回顾日期',
        taskEditorFieldAttachments: '附件',
        taskEditorFieldChecklist: '清单',
        taskEditorFieldTextDirection: '文本方向',
        featurePriorities: '优先级',
        featurePrioritiesDesc: '为任务显示优先级标记。',
        featureTimeEstimates: '时间估算',
        featureTimeEstimatesDesc: '为时间管理添加时长估计。',
        featurePomodoro: '番茄钟',
        featurePomodoroDesc: '在聚焦视图中启用可选的番茄钟面板。',
        notifications: '通知',
        notificationsDesc: '启用任务提醒与每日简报通知。',
        notificationsEnable: '启用通知',
        reviewAtNotifications: '回顾日期提醒',
        reviewAtNotificationsDesc: '在回顾（tickler）日期到期时提醒我。',
        ai: 'AI 助手',
        aiDesc: '帮助澄清与拆解任务（可选）。',
        aiEnable: '启用 AI 助手',
        aiProvider: '服务商',
        aiProviderOpenAI: 'OpenAI',
        aiProviderGemini: 'Gemini',
        aiProviderAnthropic: 'Anthropic（Claude）',
        aiModel: '模型',
        aiBaseUrl: '自定义基础 URL',
        aiBaseUrlHint: '可选。用于本地 OpenAI 兼容服务（例如 http://localhost:11434/v1）。',
        aiApiKey: 'API 密钥',
        aiApiKeyHint: '仅保存在本机，不会同步。本地端点若无需鉴权可留空。',
        aiReasoning: '推理强度',
        aiReasoningHint: '仅用于 GPT-5 模型。',
        aiEffortLow: '低',
        aiEffortMedium: '中',
        aiEffortHigh: '高',
        aiCopilotModel: '助手模型',
        aiCopilotHint: '用于快速补全建议。',
        aiConsentTitle: '启用 AI 功能？',
        aiConsentDescription: '要使用此功能，您的任务数据将发送到 {provider} 进行处理。该数据受其隐私政策约束。Mindwtr 不会收集这些数据。是否继续？',
        aiConsentCancel: '取消',
        aiConsentAgree: '同意',
        aiThinkingBudget: '思考预算',
        aiThinkingHint: '仅用于 Claude/Gemini。0 代表关闭深度思考。',
        aiThinkingEnable: '启用思考',
        aiThinkingEnableDesc: '为复杂任务启用扩展推理。',
        aiThinkingOff: '关闭',
        aiThinkingLow: '低',
        aiThinkingMedium: '中',
        aiThinkingHigh: '高',
        speechTitle: '语音转文字',
        speechDesc: '转录语音并映射到任务字段。',
        speechEnable: '启用语音转文字',
        speechProvider: '语音服务商',
        speechProviderOffline: '本地（Whisper）',
        speechModel: '语音模型',
        speechOfflineModel: '离线模型',
        speechOfflineModelDesc: '下载一次即可离线转录。',
        speechOfflineReady: '模型已下载',
        speechOfflineNotDownloaded: '尚未下载模型',
        speechOfflineDownload: '下载',
        speechOfflineDownloadSuccess: '下载完成',
        speechOfflineDelete: '删除',
        speechOfflineDownloadError: '离线模型下载失败',
        speechLanguage: '语音语言',
        speechLanguageHint: '可填写语言名称或代码，留空则自动检测。',
        speechLanguageAuto: '自动检测语言',
        speechMode: '处理模式',
        speechModeHint: '智能解析可提取日期与字段，纯转录仅输出文本。',
        speechModeSmart: '智能解析',
        speechModeTranscript: '仅转录',
        speechFieldStrategy: '字段映射',
        speechFieldStrategyHint: '选择默认写入标题或描述的位置。',
        speechFieldSmart: '智能',
        speechFieldTitle: '标题',
        speechFieldDescription: '描述',
        dailyDigest: '每日简报',
        dailyDigestDesc: '早间简报与晚间回顾提醒。',
        dailyDigestMorning: '早间简报',
        dailyDigestEvening: '晚间回顾',
        weeklyReview: '每周回顾',
        weeklyReviewDesc: '在你设定的时间提醒进行每周回顾。',
        weeklyReviewDay: '回顾日期',
        weeklyReviewTime: '回顾时间',
        weeklyReviewConfig: '每周回顾流程',
        weeklyReviewConfigDesc: '配置每周回顾中显示哪些步骤。',
        weeklyReviewIncludeContextsStep: '包含情境步骤',
        weeklyReviewIncludeContextsStepDesc: '在“等待中”和“项目”之间显示专门的情境回顾步骤。',
        on: '开启',
        off: '关闭',
        visible: '显示',
        hidden: '隐藏',
        manage: '管理',
        diagnostics: '诊断',
        diagnosticsDesc: '帮助排查问题。',
        debugLogging: '调试日志',
        debugLoggingDesc: '将错误记录到本地以便提交反馈。',
        logFile: '日志文件',
        clearLog: '清除日志',
        sync: '同步',
        syncDescription:
            '配置一个辅助文件夹来同步您的数据（如 Dropbox、Syncthing）。若需要更实时的多设备同步，建议优先使用 WebDAV。',
        syncBackend: '同步后端',
        syncBackendOff: '关闭',
        syncBackendFile: '文件',
        syncBackendWebdav: 'WebDAV',
        syncBackendCloud: '自托管',
        syncPreferences: '设置同步选项',
        syncPreferencesDesc: '选择要在设备间同步的偏好设置。',
        syncPreferenceAppearance: '外观（主题、密度）',
        syncPreferenceLanguage: '语言与日期格式',
        syncPreferenceExternalCalendars: '外部日历 URL',
        syncPreferenceAi: 'AI 设置（模型、提供商）',
        syncPreferenceAiHint: 'API 密钥和本地模型路径不会同步。',
        attachmentsCleanup: '附件清理',
        attachmentsCleanupDesc: '从设备和同步存储中删除已删除或孤立的附件文件。',
        attachmentsCleanupLastRun: '上次清理',
        attachmentsCleanupNever: '从未',
        attachmentsCleanupRun: '立即清理',
        attachmentsCleanupRunning: '清理中...',
        calendar: '日历',
        calendarDesc: '通过 ICS 订阅地址查看外部日历（只读）。',
        externalCalendars: '外部日历',
        calendarName: '名称',
        calendarUrl: 'ICS 地址',
        calendarAdd: '添加日历',
        calendarRemove: '移除',
        calendarSystemTitle: 'Apple 日历（macOS）',
        calendarSystemDesc: '通过 EventKit 读取 macOS 已同步的 Apple 日历账户（iCloud、Google、Exchange）事件。',
        calendarSystemStatus: 'Apple 日历访问',
        calendarSystemPermissionGranted: '已授权',
        calendarSystemPermissionUndetermined: '未请求',
        calendarSystemPermissionDenied: '已拒绝',
        calendarSystemPermissionUnsupported: '不支持',
        calendarSystemRequestAccess: '请求访问',
        calendarSystemDeniedHint: '日历访问被拒绝。请在 macOS 系统设置 > 隐私与安全性 > 日历 中为 Mindwtr 开启权限。',
        syncFolderLocation: '同步文件夹',
        savePath: '保存',
        browse: '浏览…',
        syncNow: '立即同步',
        syncing: '同步中…',
        syncQueued: '同步已排队',
        pathHint: '请选择文件夹（如 ~/Sync/mindwtr）。使用 Syncthing 时建议开启 Send & Receive 与 Watch for Changes，并在切换设备前手动点“立即同步”。',
        webdavUrl: 'WebDAV 地址',
        webdavUsername: '用户名',
        webdavPassword: '密码',
        webdavSave: '保存 WebDAV',
        webdavHint: '请输入同步文件夹地址，Mindwtr 会在其中存放 data.json（例如 https://example.com/remote.php/dav/files/user/mindwtr）。',
        cloudUrl: '自托管地址',
        cloudToken: '访问令牌',
        cloudSave: '保存自托管配置',
        cloudHint: '请输入自托管基础地址（例如 https://example.com/v1），Mindwtr 会自动追加 /data。',
        cloudProvider: '云服务提供方',
        cloudProviderSelfHosted: '自托管',
        cloudProviderDropbox: 'Dropbox',
        dropboxAppKey: 'Dropbox 账号',
        dropboxAppKeyHint: 'Dropbox App Key 在构建/发布时注入。',
        dropboxRedirectUri: '回调地址',
        dropboxStatus: '状态',
        dropboxConnected: '已连接',
        dropboxNotConnected: '未连接',
        dropboxConnect: '连接 Dropbox',
        dropboxDisconnect: '断开 Dropbox',
        dropboxTest: '测试连接',
        dropboxTestReachable: '可访问',
        dropboxTestFailed: '失败',
        lastSync: '上次同步',
        lastSyncNever: '从未同步',
        lastSyncSuccess: '同步完成',
        lastSyncError: '同步失败',
        lastSyncConflict: '已解决冲突',
        lastSyncConflicts: '冲突',
        lastSyncSkew: '时钟偏差',
        lastSyncAdjusted: '时间修正',
        lastSyncConflictIds: '冲突 ID',
        syncHistory: '同步历史',
        recoverySnapshots: '恢复快照',
        recoverySnapshotsDesc: '同步前创建。最多保留 7 天（最多 5 个文件）。',
        recoverySnapshotsLoading: '正在加载快照…',
        recoverySnapshotsEmpty: '暂无快照。',
        recoverySnapshotsRestore: '恢复',
        recoverySnapshotsConfirm: '恢复快照 {snapshot}？这将替换当前本地数据。',
        recoverySnapshotsConfirmTitle: '恢复快照？',
        recoverySnapshotsConfirmCancel: '取消',
        about: '关于',
        version: '版本',
        developer: '开发者',
        website: '开发者网站',
        github: 'GitHub',
        documentation: '文档',
        sponsorProject: '赞助项目',
        license: '许可证',
        checkForUpdates: '检查更新',
        checkStoreUpdates: '检查 Microsoft Store 更新',
        checking: '检查中…',
        upToDate: '您正在使用最新版本！',
        updateAvailable: '有可用更新',
        checkFailed: '检查更新失败',
        storeUpdateHint: '更新由 Microsoft Store 管理。',
        download: '下载',
        downloadStarting: '正在打开下载…',
        downloadStarted: '已在浏览器开始下载。',
        downloadFailed: '打开下载链接失败。',
        downloadChecksumMismatch: '校验和验证失败，请从发布页面重新下载。',
        downloadRecommended: '推荐下载包',
        downloadAURHint: '检测到 Arch：建议使用 AUR 更新',
        changelog: '更新日志',
        noChangelog: '暂无更新日志',
        later: '稍后',
        linuxUpdateHint: 'Linux 上无法自动安装更新。下载后请使用包管理器更新（如 yay -S mindwtr 或 paru -S mindwtr），或安装下载的包。',
        saved: '设置已保存',
        selectSyncFolderTitle: '选择同步文件夹',
        system: '系统',
        light: '浅色',
        dark: '深色',
        eink: '电子墨水',
        nord: 'Nord',
        sepia: '复古米黄',
    },
} as const;

export type SettingsLabels = Record<keyof typeof labelFallback.en, string>;

export const labelKeyOverrides: Partial<Record<keyof SettingsLabels, string>> = {
    back: 'common.back',
    keybindings: 'keybindings.helpTitle',
    keybindingsDesc: 'settings.keybindingsDesc',
    keybindingVim: 'keybindings.style.vim',
    keybindingEmacs: 'keybindings.style.emacs',
    viewShortcuts: 'keybindings.openHelp',
    dateFormat: 'settings.dateFormat',
    dateFormatSystem: 'settings.dateFormatSystem',
    dateFormatDmy: 'settings.dateFormatDmy',
    dateFormatMdy: 'settings.dateFormatMdy',
    taskEditorLayoutReset: 'settings.resetToDefault',
    taskEditorFieldStatus: 'taskEdit.statusLabel',
    taskEditorFieldProject: 'taskEdit.projectLabel',
    taskEditorFieldSection: 'taskEdit.sectionLabel',
    taskEditorFieldArea: 'taskEdit.areaLabel',
    taskEditorFieldPriority: 'taskEdit.priorityLabel',
    taskEditorFieldContexts: 'taskEdit.contextsLabel',
    taskEditorFieldDescription: 'taskEdit.descriptionLabel',
    taskEditorFieldTags: 'taskEdit.tagsLabel',
    taskEditorFieldTimeEstimate: 'taskEdit.timeEstimateLabel',
    taskEditorFieldRecurrence: 'taskEdit.recurrenceLabel',
    taskEditorFieldStartTime: 'taskEdit.startDateLabel',
    taskEditorFieldDueDate: 'taskEdit.dueDateLabel',
    taskEditorFieldReviewAt: 'taskEdit.reviewDateLabel',
    taskEditorFieldAttachments: 'attachments.title',
    taskEditorFieldChecklist: 'taskEdit.checklist',
    taskEditorFieldTextDirection: 'taskEdit.textDirectionLabel',
} as const;
