name: mindwtr
base: core22
version: '0.6.14'
summary: Local-first GTD application
description: |
  Mindwtr is a privacy-focused, local-first GTD app for desktop.
grade: stable
confinement: strict

apps:
  mindwtr:
    command: usr/bin/mindwtr
    extensions: [gnome]
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11

parts:
  mindwtr:
    plugin: dump
    source: apps/desktop/src-tauri/target/release/bundle/deb/mindwtr_0.6.14_amd64.deb
    source-type: deb
